### ISSUE TITLE
IllegalArgumentException when using domain socket

### ISSUE THREAD

**Issue by ankushs92** [vert-x3/vertx-redis-client#102]
### Version

* vert.x core: 3.5.1
* vert.x redis client: 3.5.1

### Context

I am trying to connect to Redis via domain socket. I have already configured redis to use unix socket. This **https://github.com/vert-x3/vertx-redis-client/issues/90** issue suggests that unix socket has been implemented in vert.x 3.5.1, although I could not find any documentation on [vertx-redis ](https://vertx.io/docs/vertx-redis-client/java/) page.

### Do you have a reproducer?
Here's how I have configured RedisClient

```groovy
    @Bean("redis")
    RedisClient redis() {
        def options = new RedisOptions()
        options.domainSocket = true
        options.domainSocketAddress = "/tmp/redis.sock"
        def redis = RedisClient.create(vertx, options)
        redis
    }
```
I am performing a simple hset operation. The error is : 

``` java
java.lang.IllegalArgumentException: null
	at io.vertx.core.net.impl.transport.Transport.channelType(Transport.java:157) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:176) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:165) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:160) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.redis.impl.RedisConnection.connect(RedisConnection.java:139) ~[vertx-redis-client-3.5.1.jar:3.5.1]
	at io.vertx.redis.impl.RedisConnection.lambda$connect$7(RedisConnection.java:215) ~[vertx-redis-client-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) ~[netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.19.Final.jar:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]

```

### Extra

I've used Lettuce in the past successfully to connect to Redis via domain socket. But I had to add the following dependencies for it to work : 

```groovy
	//For production environments
	compile group: 'io.netty', name: 'netty-transport-native-kqueue', version: '4.1.16.Final', classifier : 'osx-x86_64'

	//For development on mac
	compile group: 'io.netty', name: 'netty-transport-native-epoll', version: '4.1.16.Final', classifier : 'linux-x86_64'

```

Tried the same with vertx-redis client, but got the same error.

**Comment by BillyYccc** [comment]
Have you checked with the `vertx.isNativeTransportEnabled()`?

**Comment by ankushs92** [comment]
Well, not until you pointed it out. I updated my vert.x config which now looks like this : 
``` groovy
def options = new VertxOptions().setPreferNativeTransport(true)
def vertx = Vertx.vertx(options)
```
And then I just use that vertx instance. There is no official or unofficial documentation on how to actually work with redis with domain sockets with vertx-redis-client though. Since you were the dev who contributed this feature, do you mind sharing a gist on how to use it? I'd really appreciate it.

**Comment by vietj** [comment]
check that the vertx instance isNativeTransportEnabled() returns true after you created it, there might be errors that prevented to load native sockets

**Comment by vietj** [comment]
in case it returns false, you can get a Throwable from io.vertx.core.net.impl.transport.Transport.unavailabilityCause() that you can print

I think this exception should be exposed in the vertx instance

**Comment by BillyYccc** [comment]
I have written some code in https://gist.github.com/BillyYccc/7f0d1d5a6a6d3a1f3e91b0852c59a2b5, this works for me in Linux.

Don't forget to add the dependency below in addition to the `vertx-core` and `vertx-redis-client`
```
<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-transport-native-epoll</artifactId>
  <version>4.1.15.Final</version>
  <classifier>linux-x86_64</classifier>
</dependency>
```

Note if you don't specify `setPreferNativeTransport(true)` in `VertxOptions` and you still connect with a domain socket, this will indeed throw an `IllegalArgumentException`, so I guess you should check the `vertx` instance options carefully.
