### ISSUE TITLE
rxClusterNodes can not use

### ISSUE THREAD

**Issue by zuosc** [vert-x3/vertx-redis-client#117]
### Version

* vert.x core:3.5.3
* vert.x redis client:3.5.3

This is Code:

```
    suspend fun InitRedis(ip: String, port: Int) {
        val config = RedisOptions()
        config.host = ip
        config.port = port

        val client = RedisClient.create(VertxManager.getVertx(), config)

        val data = client.rxClusterNodes().await()
        logger.info(data)
    }
```

error info:
```
io.vertx.core.impl.ContextImpl
严重: Unhandled exception
java.lang.ClassCastException: io.vertx.core.buffer.impl.BufferImpl cannot be cast to [Lio.vertx.redis.impl.Reply;
	at io.vertx.redis.impl.Reply.asType(Reply.java:94)
	at io.vertx.redis.impl.RedisConnection.handleReply(RedisConnection.java:460)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:169)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:21)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:384)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:242)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:239)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

I think  the return  value is not JsonArray...

**Comment by pmlopes** [comment]
New API is type safe and doesn't do automatic casts to avoid this.
