### ISSUE TITLE
Redis client is blocking the event loop

### ISSUE THREAD

**Issue by dklotz** [vert-x3/vertx-redis-client#118]
### Version

* vert.x core: 3.5.4
* vert.x redis client: 3.5.4

### Context

When I first do a redis command (`get`, `set`, ...), the client seems to internally lazily initate the connection, but seems to do so in a blocking way on an event loop thread, which is not a good idea. See the simple reproducer and look at the output it produces. The get immediately returns control to the main thread (thats why "Done" is printed before the warnings), so the blocking definitely comes from somewhere inside the client, not my application code using it.

### Do you have a reproducer?

* https://gist.github.com/dklotz/244258d80f96231517e5ee70c8c806b5

### Steps to reproduce

1. Create a Vert.x redis client.
2. Send the first command.
3. See Vert.x complain about a blocked event loop thread.

### Extra

* If the client needs to do something that blocks on first connection, it should probably move it to a worker thread and not do it on one of the main vert.x event loop threads.

**Comment by tsegismont** [comment]
@dklotz can you reduce the time before the block thread checker prints a stacktrace? So that we get a better idea of what's going wrong. Thanks

**Comment by dklotz** [comment]
@tsegismont Sure, setting `warningExceptionTime` to `1000` gives me this stack trace:

```
Oct 22, 2018 12:39:01 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2812 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	at sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:140)
	at sun.management.RuntimeImpl.getName(RuntimeImpl.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:120)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:77)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:111)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:83)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:58)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:102)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:92)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:85)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:49)
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:230)
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:165)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:160)
	at io.vertx.redis.impl.RedisConnection.connect(RedisConnection.java:139)
	at io.vertx.redis.impl.RedisConnection.lambda$connect$7(RedisConnection.java:215)
	at io.vertx.redis.impl.RedisConnection$$Lambda$9/329645619.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.vertx.core.impl.ContextImpl$$Lambda$10/1050349584.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tsegismont** [comment]
@dklotz thanks for keeping us informed!
