### ISSUE TITLE
RedisClientImpl throws NullPointerException if key is not present in Redis while calling getBinary(String key, Handler<AsyncResult<Buffer>> handler)

### ISSUE THREAD

**Issue by vtutrinov** [vert-x3/vertx-redis-client#141]
### Version

* vert.x core: 3.7.0
* vert.x redis client: 3.7.0

### Do you have a reproducer?

* https://github.com/vtutrinov/vertx-redis-client-3.7.0-npe-test

### Log
`java.lang.NullPointerException: null
	at io.vertx.redis.impl.RedisClientImpl.lambda$sendBuffer$7(RedisClientImpl.java:223)
	at io.vertx.redis.client.impl.RedisClient.handle(RedisClient.java:341)
	at io.vertx.redis.client.impl.RESPParser.handleResponse(RESPParser.java:228)
	at io.vertx.redis.client.impl.RESPParser.handleResponse(RESPParser.java:186)
	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:121)
	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:25)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:393)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:230)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:120)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:371)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:390)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by okou19900722** [comment]
I got same issue; when I invoke `hmget`, it throw NullpointerException

**Comment by okou19900722** [comment]
Unit test was commented
