### ISSUE TITLE
Vertx 3.7.0: Unable to connect to redis, Redis connection is broken

### ISSUE THREAD

**Issue by prakharmishra** [vert-x3/vertx-redis-client#152]
### Version

* vert.x core: 3.7.0
* vert.x redis client: 3.7.0

### Context

I encountered an exception which looks suspicious while testing my code:

```
@RunWith(VertxUnitRunner.class)
public class TestRedisConnectivity {
    private static Vertx vertx;

    @BeforeClass
    public static void startUp(TestContext context) {
        vertx = Vertx.vertx();
        context.async().complete();
    }

    @AfterClass
    public static void tearDown(TestContext context) {
        vertx.close(context.asyncAssertSuccess());
    }

    @Test(timeout = 10000)
    public void testRedisDBConnectivity(TestContext context) {
        Async async = context.async();

        RedisOptions redisOptions = new RedisOptions()
                .setEndpoint(new SocketAddressImpl(6379, "192.168.2.4"))
                .setSelect(0);

        Redis.createClient(vertx, redisOptions)
                .connect(onConnect -> {
                    if (onConnect.succeeded()) {
                        context.assertTrue(true, "Connected to redis");
                    } else {
                        onConnect.cause().printStackTrace();
                        context.assertTrue(false, "Unable to connect to redis");
                    }

                    async.complete();
                });
    }
}
```
Exception is as follows:
```
io.vertx.core.impl.NoStackTraceThrowable: Redis connection is broken.

java.lang.AssertionError: Unable to connect to redis. Expected true
```

### Do you have a reproducer?
See code above

### Steps to reproduce

1. Include `vertx-core`, `vertx-redis-client`, `junit` and `vertx-unit` dependencies in pom.xml
2. Create a test case with code pasted above
3. Run the test

**Comment by pmlopes** [comment]
Thanks for the report @prakharmishra I'll investigate

**Comment by Tinadim** [comment]
@pmlopes are there any workarounds for this until it gets released? I'm writing a project that depends on Redis and I'm facing the same issue.

**Comment by An0nymous0** [comment]
release time？

**Comment by Tinadim** [comment]
@An0nymous0 looks like 3.7.1 has been released a few days ago and it seems to have the fix

**Comment by zoeminghong** [comment]
on 3.7.1 will cause this error when value was not null.

```
java.lang.NullPointerException: null
	at io.vertx.redis.impl.RedisClientImpl.lambda$sendLong$3(RedisClientImpl.java:149)
	at io.vertx.redis.client.impl.RedisClient.handle(RedisClient.java:358)
	at io.vertx.redis.client.impl.RESPParser.handleResponse(RESPParser.java:228)
	at io.vertx.redis.client.impl.RESPParser.handleResponse(RESPParser.java:186)
	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:109)
	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:25)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:393)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:230)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:120)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:371)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:390)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Alars-ALIT** [comment]
I still get:
java.lang.NullPointerException: null
	at io.vertx.redis.impl.RedisClientImpl.lambda$sendLong$3(RedisClientImpl.java:149)
...
.. in 3.8.1
