### ISSUE TITLE
Weird problem when sending request to a basic Vert.x server with a basic Redis client.

### ISSUE THREAD

**Issue by poiuytrez** [vert-x3/vertx-redis-client#17]
I am currently working on a project where I need to receive an id number through a requests and then look if it is stored in my Redis database.

My project works well for one request or two, but when testing it with Jmeter and sending 3000 requests I noticed a weird problem.

I made a way more basic project and I published it to github to understand what was going on. 

There is actually two problems : 

- The first one being that sometimes my project won't respond to Jmeter after like responding 200 requests or so... Jmeter keeps waiting for the reply.

- The other one is that sometimes I get this exception, it has the same effect on Jmeter than the first one.

io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.RuntimeException: Received a non pub/sub message without reply handler waiting:io.vertx.redis.impl.Reply@6a3c7ffb
at io.vertx.redis.impl.RedisConnection.handleReply(RedisConnection.java:92)
at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:154)
at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:6)
at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:309)
at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$27(VertxNetHandler.java:54)
at io.vertx.core.net.impl.VertxNetHandler$$Lambda$47/140297772.run(Unknown Source)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:312)
at io.vertx.core.impl.ContextImpl$$Lambda$6/60559178.run(Unknown Source)
at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:217)
at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:54)
at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
at java.lang.Thread.run(Thread.java:745)

The error really seems to be coming from my code since when I try to respond the request instantly without even calling my Redis client I manage to go through the whole 3000 requests without any problem. 
I am using Vert.x 3.0.

**Comment by poiuytrez** [comment]
I will be glad to send you a virtual beer :+1:

**Comment by pmlopes** [comment]
i think i've fixed it, the issue is related to handlers not being called in the right context so when there is lots of load even though the handler is called the context is wrong and there is no reference to the correct request... i am still testing it more and will make a pr this afternoon

**Comment by poiuytrez** [comment]
Great ! Thank you !
http://beeroverip.org/random/

**Comment by pmlopes** [comment]
@poiuytrez the issue is still being fixed, please follow the pr #18
