### ISSUE TITLE
New connection pool seems broken

### ISSUE THREAD

**Issue by zenios** [vert-x3/vertx-redis-client#189]
### Version

* vert.x core:4.0.0-milestone3
* vert.x redis client: 4.0.0-milestone3

### Context

I made a simple verticle that every 1s takes and releases a connection. After 4 executions, acquiring connection fails with io.vertx.core.http.ConnectionPoolTooBusyException: Connection pool reached max wait queue size of 1

### Do you have a reproducer?
```java

public class RedisVerticle extends AbstractVerticle {
    @Override
    public void start() {
        Redis client = Redis.createClient(vertx);
        vertx.setPeriodic(1000, event -> {
            client.connect(event1 -> {
                if (event1.succeeded()) {
                    System.out.println("Connection acquired");
                    event1.result().close();
                } else
                    event1.cause().printStackTrace();
            });
        });
    }
}
```

> Connection acquired
Connection acquired
Connection acquired
Connection acquired
io.vertx.core.http.ConnectionPoolTooBusyException: Connection pool reached max wait queue size of 1
	at io.vertx.core.http.impl.pool.Pool.lambda$nextTask$1(Pool.java:300)
	at io.vertx.core.http.impl.pool.Pool.checkPendingTasks(Pool.java:256)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by vietj** [comment]
thanks, it seems that the close does not properly release the connection to the pool

**Comment by vietj** [comment]
we should actually rename the exception to be HTTP agnostic in vertx-core in master
