### ISSUE TITLE
io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster

### ISSUE THREAD

**Issue by lygoing** [vert-x3/vertx-redis-client#223]
### Questions

```

io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster


java.lang.AssertionError: io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster

	at io.vertx.junit5.VertxExtension.joinActiveTestContexts(VertxExtension.java:226)
	at io.vertx.junit5.VertxExtension.afterTestExecution(VertxExtension.java:197)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterTestExecutionCallbacks$8(TestMethodTestDescriptor.java:221)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:256)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:256)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:255)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterTestExecutionCallbacks(TestMethodTestDescriptor.java:220)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster

```

### Version

os: debian 9 amd64
jdk: 11.0.6
vertx-redis-client：3.9.0
redis: 5.0.7

### Context

The redis cluster contains 6 nodes, 3 master nodes and 3 slave nodes。The redis service is deployed on the cloud server, and I use the public IP connection. Works fine in redisdesktopmanager

### Do you have a reproducer?

Public network IP uses `xxxx` instead

```

RedisOptions redisOptions = new RedisOptions()
                .setType(RedisClientType.CLUSTER)
                .addConnectionString("redis://:flight531@xxxx:26302")
                .addConnectionString("redis://:flight531@xxxx:26303")
                .addConnectionString("redis://:flight531@xxxx:26305")
                .addConnectionString("redis://:flight531@xxxx:26301")
                .addConnectionString("redis://:flight531@xxxx:26304")
                .addConnectionString("redis://:flight531@xxxx:26306")
                .setNetClientOptions(new NetClientOptions()
                        .setTcpKeepAlive(true)
                        .setTrustAll(true)
                        .setTcpFastOpen(true)
                        .setTcpNoDelay(true)
                );

        this.client = Redis.createClient(vertx, redisOptions).connect(onConnect -> {
            if (onConnect.succeeded()) {
                vertx.deployVerticle(new CacheVerticle(this.client));
                startPromise.complete();
            } else {
                Throwable throwable = onConnect.cause();
                startPromise.fail(throwable);
            }
        });
        super.start();

```

I found some abnormal situations through the debug interface.
- The first connected IP address becomes the internal network IP address, but the configuration uses the public network IP address
- There is no password in all node connection URL

![image](https://user-images.githubusercontent.com/5944432/79190397-ca078880-7e56-11ea-82e4-6deeb68a25ee.png)

**Comment by lygoing** [comment]
I redeployed the redis cluster service, and now I don't need to connect via password. Through debugging, I found that some nodes can connect correctly, but at the same time there is a connection timeout. From the screenshot, we know that the connection IP is a LAN IP address.

![image](https://user-images.githubusercontent.com/5944432/79209984-bec45500-7e76-11ea-98ba-21d4945768e1.png)

**Comment by lygoing** [comment]
I found a magical configuration in the redis desktop manager. Selecting this item will also cause an error when the cluster is connected. It seems that the two belong to the same problem? Any help? thanks a million.

![image](https://user-images.githubusercontent.com/5944432/79485023-26c99580-8047-11ea-87d4-93289ccfa4c6.png)

**Comment by pmlopes** [comment]
See #222 we don't support password on cluster or sentinel yet.

**Comment by lygoing** [comment]
@pmlopes  Thanks for your replay.

Secondly, there is a problem that the acquired IP becomes an intranet IP address, which is obviously not accessible on the public network.

**Comment by pmlopes** [comment]
That's more complicated because I don't see how to correlate the given ip to the translated internal ip. It may depend on each node dns settings.

If you uncheck that box, will it return the public ip always?

**Comment by pmlopes** [comment]
Alternatively we can have a global password that shall be applied to a node which is unknown to the user given list. The only issue is that misconfigured clients may leak the password to a bad rogue server. If we can live with that fact it could be possible.

**Comment by lygoing** [comment]
In the redis desktop manager, uncheck it to work, if it is checked, you can see the ip address jump to the intranet IP in the console, then the connection failure is displayed!

This is my redis server, it is a cluster and I cancelled the password. `172.81.237.168:26301`

**Comment by lygoing** [comment]
I remember that the previous API seems to have a global password setting? `setPassword ()`, as for security issues, no password can be accepted in my application because the servers are all on the intranet. But maybe someone will care about it

**Comment by pmlopes** [comment]
Ok, so let's bring back the global password for connections started internally in cluster or sentinel mode.

**Comment by pendula95** [comment]
For the second part of the issue. In order for this kind of setup to work where redis nodes will return private/internal IPs and in configuration we setup public IPs can't we group join public IP (configured) and private/internal IPs by their redis node ids.
For this to work I assume that all nodes need to be added in configuration.

**Comment by pendula95** [comment]
@lygoing if this checkbox is unchecked and for example resharding happens how does driver handle redirect response from node as it will contain private IP that driver does not now how to handle. driver = redis desktop manager

**Comment by chulong** [comment]
hello ,How do you solve the problem of Intranet IP?
