### ISSUE TITLE
when an idle connection with a pika server is closed by the server, the redisClient will break on next user call,without throwing an exception that can be catched by user

### ISSUE THREAD

**Issue by infbox** [vert-x3/vertx-redis-client#227]
### Questions

`五月 01, 2020 1:33:27 下午 io.vertx.redis.client.impl.ConnectionManager
严重: Unhandled Error
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:124)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
	at io.vertx.core.net.impl.NetSocketImpl.writeMessage(NetSocketImpl.java:130)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:174)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:168)
	at io.vertx.redis.client.impl.RedisConnectionImpl.lambda$send$1(RedisConnectionImpl.java:131)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

### Version

3.9.0

### Context

I encountered a bug  while I used the redisClient to connect to a pika server(a redis-protocol-compatible K-V server).when an idle connection with a pika server is closed by the server, the redisClient will break on next user call,without throwing an exception that can be catched by user.
but this situation will not occur when connected with redis server. this problem is only subject to pika.

### Do you have a reproducer?
I have no reproducer.
### Steps to reproduce

1.  run a pika server with timeout set to 60 seconds
2. create a redisClient for the pika server
`RedisOptions option=new RedisOptions().setHost(host).setPort(port);
redisClient =RedisClient.create(vertx,option);
redisClient.auth(passwd,r->{});
`
3. run vertx client program , and invoke a call to the redisClient after the program is started, you can see everything is okay. but when you call again after a longger-than-60-senconds interval, you will encounter this problem:the call can nerver get feedback ,and the above exception can't be catched .

**Comment by wem** [comment]
You are able to catch network related exceptions with `RedisConnection.exceptionHandler`. You may could obtain a connection with `Redis.connect` and call `RedisConnection.send` afterward, instead of `Redis.send` directly, so you get notified about connection issues.

**Comment by infbox** [comment]
thanks for your reply. But I can't figure out how to use the RedisConnection.send(Request,Handler) api ,since both the vertx doc page and the official examples do not explain how to set Request parameter with commands like setex,mset ,get.  maybe the official examples of vertx-redis-client should be updated now.

**Comment by wem** [comment]
Here is an example class that should show both approaches. The second provides the functionality you may are looking for ... I hope this help:

```
public class RedisRepository {

    private final Redis redis;

    public RedisRepository(Redis redis) {
        this.redis = redis;
    }

    /**
     * In this variant you call "send" directly. The client itself will get a connection, but you are not able to handle
     * issues on the connection itself.
     * @param incrBy
     * @param resultHandler
     */
    public void incrementKeyOnClient(Integer incrBy, Handler<AsyncResult<Integer>> resultHandler) {
        redis.send(Request.cmd(Command.INCRBY).arg(incrBy), incrResult -> {
            if (incrResult.succeeded()) {
                resultHandler.handle(Future.succeededFuture(incrResult.result().toInteger()));
            } else {
                resultHandler.handle(Future.failedFuture(incrResult.cause()));
            }
        });
    }

    /**
     * Here you call the command to Redis directly on a specific connection instead of the client. This enables you
     * to do your own error handling as documented "https://vertx.io/docs/vertx-redis-client/java/#_implementing_reconnect_on_error"
     * @param incrBy
     * @param resultHandler
     */
    public void incrementKeyOnConnection(Integer incrBy, Handler<AsyncResult<Integer>> resultHandler) {
        redis.connect(connectResult ->  {
            if (connectResult.succeeded()) {
                final RedisConnection connection = connectResult.result();
                // That's the point of difference, as you call the command on an explicit connection instead
                connection.exceptionHandler(exception -> resultHandler.handle(Future.failedFuture(exception)));

                // From callers side the same thing as on the client directly.
                connection.send(Request.cmd(Command.INCRBY).arg(incrBy), incrResult -> {
                    if (incrResult.succeeded()) {
                        resultHandler.handle(Future.succeededFuture(incrResult.result().toInteger()));
                    } else {
                        resultHandler.handle(Future.failedFuture(incrResult.cause()));
                    }
                });
                // Important, so the connection goes back to pool
                connection.close();
            } else {
                resultHandler.handle(Future.failedFuture(connectResult.cause()));
            }
        });
    }
}
```

**Comment by wem** [comment]
Btw ... this PR relates to this problem i think https://github.com/vert-x3/vertx-redis-client/pull/226

**Comment by pmlopes** [comment]
@infbox this seems to be a bug at netty level (the IO library). The exception should not be thrown but passed back to the callback.

**Comment by vietj** [comment]
I looked at the code and wrote this reproducer, it seems that the Netty code and NetSocket code is behaving correctly.

```java
    Vertx vertx = Vertx.vertx();
    NetClient client = vertx.createNetClient();
    vertx.createNetServer().connectHandler(so -> {
      so.close();
    }).listen(1234, "localhost").flatMap(s -> client
      .connect(1234, "localhost")
    ).onSuccess(so -> {
      so.closeHandler(v -> {
        System.out.println("closed");
        so.write("abc").onComplete(ar -> {
          ar.cause().printStackTrace();
        });
      });
    });
```

will produce

```
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:150)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:190)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:186)
	at io.vertx.core.net.impl.NetSocketImpl.writeMessage(NetSocketImpl.java:130)
	at io.vertx.core.net.impl.NetSocketImpl.writeMessage(NetSocketImpl.java:124)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:153)
	at io.vertx.core.Main.lambda$null$3(Main.java:18)
	at io.vertx.core.net.impl.ConnectionBase.checkCloseHandler(ConnectionBase.java:358)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:58)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.core.Promise.tryComplete(Promise.java:122)
	at io.vertx.core.Promise.complete(Promise.java:78)
	at io.vertx.core.net.impl.ConnectionBase.handleClosed(ConnectionBase.java:349)
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:136)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The reported stack trace does not make sense to me, I believe one should reproduce the issue and observe what is actually happening.

**Comment by pmlopes** [comment]
@infbox can you explain where you get this `pika` server how to get it running so I can debug why is this exception being thrown?

**Comment by infbox** [comment]
@pmlopes  pika is a redis-protocol-compatible KV server ,it's official adress is  https://github.com/Qihoo360/pika . 
Finally I found that , the reason why I can't catch the exception is that ,Netty throws an excepton with a null error message. so at first I wrote my catch logic as below:
`myRedisConnection.exceptionHandler(th->{
      // th.getMessage() returns null in fact which is really beyond my imagination
       String error=th.getMessage(); 
       if(error.contains("ClosedChannelException")){//error is null,so this will throw exception 
          //........
         }
}`
so , I changed my code and catched the exception in this way:
`myRedisConnection..exceptionHandler(th->{
            if(th.toString().contains("ClosedChannelException")){                      
                        myRedisConnection.close();                       
                        reconnect();
            }
}` 
now my pika client can work properly again .
@vietj   you are right, this ClosedChannelException does not set its error message.

**Comment by pmlopes** [comment]
@infbox instead of looking at the message, you could do:

```java
If (res.cause() instanceof SomeException) {
  ...
```

This would not fail and allow handling like on a try catch. Hopefully with java 15 this shall be even easier with the new switch expressions
