### ISSUE TITLE
Can't connect to azure redis

### ISSUE THREAD

**Issue by MYDIH** [vert-x3/vertx-redis-client#238]
### Version

3.9.1

### Context

When I try to connect to a Microsoft.Cache redis instance, I get an `IOException` :

```
java.io.IOException: Connexion ré-initialisée par le correspondant
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-buffer-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

I used both `redis://` and `rediss://` scheme considering that Microsoft.Cache is using SSL. I can't, for obvious reason, give the connection string I'm using but it's along those lines : 

`rediss://:<password>@<host.redis.cache.windows.net>:<port>`

PS: the error is localized, but in English it's `connexion reset by peer`

### Extra

* Java 11

**Comment by MYDIH** [comment]
Seems like SSL is only implemented in 4.0.0. It's connecting now.

Closing

**Comment by valtercorreia** [comment]
Hey @MYDIH, even though I'm also using 4.0.0 connecting to Azure Redis does not work for me.

For example, the following code never prints anything in the console with the specified connection string.
```
Redis client = Redis.createClient(vertx, "rediss://:<password>@<host.redis.cache.windows.net>:<port>");

   client.connect().onComplete(ar -> {
      if (ar.succeeded()) {
        System.out.println("Connection ok");
      } else {
        System.out.println("Connection or Operation Failed " + ar.cause());
      }
    });
```
I also allowed my IP on the Azure Redis firewall.
Do you remember if you had to do anything else for it to work?
Thanks in advance

**Comment by MYDIH** [comment]
Hi @valtercorreia, I think I just swap the dependency to 4.0.0-milestone5 if I recall well, I didn't change the code itself ...
