### ISSUE TITLE
[Question] Redis Pub/Sub

### ISSUE THREAD

**Issue by WindcodeFr** [vert-x3/vertx-redis-client#27]
Does vertx-redis-client support correctly the pub/sub system of redis.
I have some issues with the subscription part of the system.

         vertx.eventBus().<JsonObject>consumer("redis.sub.channel1", received -> {
            // do whatever you need to do with your message
            JsonObject value = received.body().getJsonObject("value");
            // the value is a JSON doc with the following properties
            // channel - The channel to which this message was sent
            // pattern - Pattern is present if you use psubscribe command and is the pattern that matched this message channel
            // message - The message payload
            System.out.println(value.encodePrettily());
        });

        RedisClient redis = RedisClient.create(vertx, new JsonObject());

        redis.subscribe(Collections.singletonList("channel1"), res -> {
            if (res.succeeded()) {
                // so something...
                RedisClient redis2 = RedisClient.create(vertx, new JsonObject());

                redis2.publish("channel1", "Hello World!", res2 -> {
                    if (res2.succeeded()) {
                        // so something...
                    }
                });
            }
        });

Publish system seems to work but the message is lost ?

**Comment by pmlopes** [comment]
@WindcodeFr which version are you using? unfortunately version 3.0.0 was shipped with that part of the code broken.  Ever since that I've worked on fixing it and adding tests for pub sub but that will not be available until 3.1 or any not yet scheduled 3.0.x release. If you are just experimenting I would suggest to try the 3.1.0-SNAPSHOT version and see if it works for you.

**Comment by WindcodeFr** [comment]
@pmlopes I'm currently using the version 3.0.0. I have try with the 3.1.0-SNAPSHOT and the Pub/Sub system seems to work correctly if we use "io.vertx.redis.channel1" as address for the consumer.

I have notice also a NullPointerException when the connection can't be open during initialization (3.1.0-SNAPSHOT).
```
[11:34:45] [GRAVE] Unhandled exception 
java.lang.NullPointerException
	at io.vertx.redis.impl.RedisConnection.lambda$connect$16(RedisConnection.java:143)
	at io.vertx.redis.impl.RedisConnection$$Lambda$19/979632275.handle(Unknown Source)
	at io.vertx.core.net.impl.NetClientImpl.doFailed(NetClientImpl.java:234)
	at io.vertx.core.net.impl.NetClientImpl.lambda$failed$104(NetClientImpl.java:230)
	at io.vertx.core.net.impl.NetClientImpl$$Lambda$22/1024249438.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:312)
	at io.vertx.core.impl.ContextImpl$$Lambda$6/1372082959.run(Unknown Source)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$161(OrderedExecutorFactory.java:91)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$1/1495242910.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Thank you for your answer. You did a great work.

**Comment by pmlopes** [comment]
Thanks for the report, I'll check the npe
