### ISSUE TITLE
NullPointerException in the RedisConnectionManager when calling any method on RedisAPI

### ISSUE THREAD

**Issue by jjasper714** [vert-x3/vertx-redis-client#329]
### Version

4.3.0

### Context

After upgrading to version 4.3.0 all of our tests using the redis client started failing due to a NullPointerException in the RedisConnectionManager. 

```
Cannot invoke "io.vertx.core.impl.ContextInternal.nettyEventLoop()" because "this.context" is null
java.lang.NullPointerException: Cannot invoke "io.vertx.core.impl.ContextInternal.nettyEventLoop()" because "this.context" is null
	at io.vertx.redis.client.impl.RedisConnectionManager.getConnection(RedisConnectionManager.java:363)
	at io.vertx.redis.client.impl.RedisClient.connect(RedisClient.java:32)
	at io.vertx.redis.client.impl.BaseRedisClient.send(BaseRedisClient.java:42)
	at io.vertx.redis.client.impl.RedisAPIImpl.send(RedisAPIImpl.java:56)
	at io.vertx.redis.client.RedisAPI.set(RedisAPI.java:2666)
```

### Reproducer

Here's a simple reproducer 

```
import io.vertx.reactivex.core.Vertx;
import io.vertx.reactivex.redis.client.Redis;
import io.vertx.reactivex.redis.client.RedisAPI;
import io.vertx.redis.client.RedisOptions;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.util.List;

@Testcontainers
public class TestVertxRedis {

    @Container
    private static final GenericContainer redis = new GenericContainer(DockerImageName.parse("redis:6.2.0-alpine")).withExposedPorts(6379);

    @Test
    public void testRedis() throws InterruptedException {
        Vertx vertx = Vertx.vertx();

        RedisOptions options = new RedisOptions().setConnectionString(String.format("redis://%s:%d", redis.getHost(), 6379));
        Redis redis = Redis.createClient(vertx, options);
        RedisAPI redisAPI = RedisAPI.api(redis);
        redisAPI.rxSet(List.of("key", "value")).blockingGet();

    }
}
```

### Steps to reproduce

1. Create instance of Vertx with `Vertx.vertx()`
2. Instantiate a Redis object using that vertx
3. Instantiate RedisAPI
4. Use RedisAPI to perform any call to redis.

### Extra

* Running on Ubuntu 20.04, openjdk version "17.0.3"

**Comment by pendula95** [comment]
Confirmed.

This is because of this https://github.com/vert-x3/vertx-redis-client/blob/4ea9552f83b3d2c4e33b644e44e5fcd97cd1a14a/src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java#L61

My best guess is that this.context = vertx.getOrCreateContext() should be called.
It was introduced here cbaa8a088cfa24f40c057a309fc070d48014ba6d

**Comment by pendula95** [comment]
I am not sure if test should be added for this, for embedded usage? Both bug and test seems to trivial for dedicated test. @pmlopes
