### ISSUE TITLE
Redisclient throwing ArrayIndexOutOfBoundsExceptions under heavy load in 3.1

### ISSUE THREAD

**Issue by aneb01** [vert-x3/vertx-redis-client#38]
Hi,

Yesterday I upgraded my project to use 3.1 but currently running into problems with code that was working fine in 3.0.

At the moment, when under heavy load or sometimes at random,  heavy redis operations are throwing exceptions.  Like zcan,zrange,lrange etc. 

I haven't created a reproducer but the code I am testing with is so basic and stripped down I can just post it here:

```

private static int counter = 0;

    public static void main(String[] args) {

        Vertx vertx = Vertx.vertx();

        RedisOptions config = new RedisOptions();
        config.setHost("192.168.99.100");
        config.setPort(6379);
        RedisClient redisClient =  new io.vertx.rxjava.redis.RedisClient(io.vertx.redis.RedisClient.create(vertx, config));

        int numberOfIterations = 200000;

        System.out.println("started");
        for (int i = 0; i < numberOfIterations; i++) {
            redisClient.zscan("gm:1:lb:0:rm:b:players","0", ScanOptions.NONE,event ->
            {
                if(event.succeeded())
                {
                }
            });
        }

    }

```

Error I am getting is

```
10 14, 2015 11:26:11 午前 io.vertx.core.impl.ContextImpl
重大: Unhandled exception
java.lang.ArrayIndexOutOfBoundsException: 13141
	at io.netty.buffer.UnpooledHeapByteBuf._getByte(UnpooledHeapByteBuf.java:292)
	at io.netty.buffer.UnpooledHeapByteBuf.getByte(UnpooledHeapByteBuf.java:287)
	at io.netty.buffer.WrappedByteBuf.getByte(WrappedByteBuf.java:205)
	at io.vertx.core.buffer.impl.BufferImpl.getByte(BufferImpl.java:74)
	at io.vertx.redis.impl.ReplyParser.parseResult(ReplyParser.java:131)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:173)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:21)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:308)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$28(VertxNetHandler.java:54)
	at io.vertx.core.net.impl.VertxNetHandler$$Lambda$20/699439032.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$14/1134865005.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:54)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

I am also getting a lot of message handler timeout errors but I figure it is maybe related to this problem.

Kind regards,

Yves

**Comment by aneb01** [comment]
maybe for testing purposes: that key I am testing with is a ZSET in my database with 1 row, 
value: a09a4013-8856-487b-ba2e-fa464b35b8fc
score: 1

**Comment by pmlopes** [comment]
@aneb01 Can you verify the fix above, i created a test and added a guard for the index out of bounds exception but i cannot reproduce it, mostly because i am using it agains redis running on my localhost i think.

**Comment by aneb01** [comment]
Perfect, will test it asap and let you know the result.

Thanks for the very fast response.

**Comment by aneb01** [comment]
Problems seems fixed.  Still running into an java.lang.ClassCastException: java.lang.Long cannot be cast to [Lio.vertx.redis.impl.Reply; error in the RedisConnection handler I did not have before but I will debug that more before creating an issue.

Either way the ArrayIndexOutOfBoundsError is fixed.

Thanks a lot!

**Comment by pmlopes** [comment]
ok, if you can, please provide more info about the ClassCastException as a new issue and I'll have a look.

**Comment by lxyu** [comment]
Have the same problem, is there a date for a release with this patch?

**Comment by pmlopes** [comment]
We are planning to release 3.2 in the coming weeks (the plan is to have it out before Christmas).

**Comment by lxyu** [comment]
Thanks, looking forward to it! :+1:
