### ISSUE TITLE
hgetall bug?

### ISSUE THREAD

**Issue by enjory520** [vert-x3/vertx-redis-client#48]
i use hgetall get hash data ,sometime will bring this error
error msg:
'''
java.lang.ArrayIndexOutOfBoundsException: 66
	at io.netty.buffer.UnpooledHeapByteBuf._getByte(UnpooledHeapByteBuf.java:292)
	at io.netty.buffer.UnpooledHeapByteBuf.getByte(UnpooledHeapByteBuf.java:287)
	at io.netty.buffer.WrappedByteBuf.getByte(WrappedByteBuf.java:205)
	at io.vertx.core.buffer.impl.BufferImpl.getByte(BufferImpl.java:74)
	at io.vertx.redis.impl.ReplyParser.parseResult(ReplyParser.java:131)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:173)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:21)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:308)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$28(VertxNetHandler.java:54)
	at io.vertx.core.net.impl.VertxNetHandler$$Lambda$56/1085121179.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$22/618696025.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:54)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

Unhandled exception 
java.lang.ClassCastException: io.vertx.core.buffer.impl.BufferImpl cannot be cast to [Lio.vertx.redis.impl.Reply;
	at io.vertx.redis.impl.Reply.asType(Reply.java:120)
	at io.vertx.redis.impl.RedisConnection.handleReply(RedisConnection.java:412)
	at io.vertx.redis.impl.RedisConnection$$Lambda$26/293542278.handle(Unknown Source)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:179)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:21)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:308)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$28(VertxNetHandler.java:54)
	at io.vertx.core.net.impl.VertxNetHandler$$Lambda$56/1085121179.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$22/618696025.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:54)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
'''

**Comment by pmlopes** [comment]
can you provide a reproducer? your exception lets me that the client expects a multi-bulk message while it got a bulk, i need some context to understand what is happening

**Comment by enjory520** [comment]
i create a RedisClient when the service create.it has been use whole cycle llfe.
and i test it by high concurrency

**Comment by pmlopes** [comment]
That is tool vague, could you please create a small test case/example showing the issue?

**Comment by enjory520** [comment]
can you give me a email address?
i sent my code to you

**Comment by pmlopes** [comment]
I'd rather have a small reproducer so we can use it later on as a regression test. Also have you tried the code with the latest git version? there have been many fixes for 3.2 release and it could happen that your issue is already fixed...

However i'd advise to write a small reproducer...

**Comment by pmlopes** [comment]
Due to inactivity and lack of a reproducer i'll close this issue, if it still happens feel free to reopen and add a reproducer.
